{% set name = "pymeos" %}
{% set version = "1.1.3a0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pymeos-{{ version }}.tar.gz
  sha256: aa1b3ccd1e8b4b955714f0c0c0c19d0360722dd73bab5e0c368bfd7b24987677

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools >=61.0
    - pip
  run:
    - python >=3.7
    - pymeos-cffi ==0.0.18
    - python-dateutil
    - spans
    - postgis
    - shapely
    - geopandas

test:
  imports:
    - pymeos
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Python wrapper for the MEOS C Library.
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Diviloper
